"""Fixed image field in Users

Revision ID: 1b6d1beebf54
Revises: b455da42085c
Create Date: 2024-01-18 17:12:42.854643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6d1beebf54'
down_revision = 'b455da42085c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_file_name',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_file_name',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)

    # ### end Alembic commands ###
